[package]
name = "model-hasher"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = {version = "4.0", features = ["derive"]}
memmap2 = "0.9.7"
safetensors = "0.6.2"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.142"
